version: "3.1"

services:
  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_blog
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
